spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      uri: http://configserver:8071
  main:
    allow-bean-definition-overriding: true
